[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]

[agents.warp_agent.input]
nld_in_terminal_enabled = true

[agents.voice]
voice_input_toggle_key = "fn"

[agents.profiles]
agent_mode_coding_permissions = "always_allow_reading"

[appearance]

[appearance.vertical_tabs]
enabled = true
view_mode = "compact"
show_details_on_hover = true
primary_info = "command"
display_granularity = "panes"
compact_subtitle = "branch"

[general]
default_session_mode = "agent"

[privacy]
telemetry_enabled = true
crash_reporting_enabled = true

[notifications]

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "dismissed"
play_notification_sound = true
